server:
  port: 8081

ingreso-service:
  port: 8082

salida-service:
  port: 8083

caja-service:
  port: 8084

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Elpeluche0323/por
          search-paths: config-data
  application:
    name: config-service
